on:
  push:
    tags:
      - '*'

name: release
jobs:
    release:
        name: run goreleaser
        runs-on: ubuntu-latest
        steps:
          - name: git checkout
            uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
            with:
              fetch-depth: 0

          - name: install go
            uses: actions/setup-go@v5
            with:
              go-version: '1.17'

          - name: Run GoReleaser
            uses: goreleaser/goreleaser-action@v6
            with:
              version: latest
              args: release --rm-dist
            env:
              GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
